// <auto-generated/>
// Sannr OpenAPI Schema Filter Generator
// Generated: 2025-12-31 12:00:00
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System;

namespace Sannr.AspNetCore
{
    /// <summary>
    /// AOT-compatible OpenAPI schema filter generated at compile-time.
    /// Applies validation rules to OpenAPI schemas without runtime reflection.
    /// </summary>
    public class SannrGeneratedSchemaFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            if (schema.Properties == null || context.Type == null)
                return;

            var typeName = context.Type.FullName;
            switch (typeName)
            {
                // Cases will be added here
                default:
                    break;
            }
        }
    }
}