<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(CompilerGeneratedFilesOutputPath)/**</DefaultItemExcludes>
    
    <!-- Centralize Package Metadata -->
    <Authors>Digvijay Chauhan</Authors>
    <Copyright>Copyright (c) 2026 Digvijay Chauhan</Copyright>
    <PackageProjectUrl>https://github.com/Digvijay/Sannr</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Digvijay/Sannr</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <!-- Make Sannr MSBuild properties visible to Source Generators -->
  <ItemGroup>
    <CompilerVisibleProperty Include="EnableSannrSchemaGen" />
    <CompilerVisibleProperty Include="SannrOpenApiVersion" />
  </ItemGroup>


  <!-- Common build settings for AOT-friendly libraries -->
  <PropertyGroup Condition="'$(IsAotCompatible)' == '' and '$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <!-- Enable high quality analysis -->
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);CA2007;CA1014</NoWarn>
  </PropertyGroup>
</Project>
