name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please provide a minimal reproduction or a code snippet.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Sannr Version
      description: What version of Sannr are you using?
      placeholder: e.g. 1.1.0
    validations:
      required: true
  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      options:
        - .NET 8.0
        - .NET 9.0 (Preview)
        - Other (please specify in description)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
